//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCode
    {
        public int id { get; set; }
        public string code { get; set; }
        public string bankName { get; set; }
        public string subType { get; set; }
        public string remarks { get; set; }
        public string contact_status { get; set; }
        public string company_codes { get; set; }
    }
}
