//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankHeadersDetail
    {
        public int Id { get; set; }
        public string BankName { get; set; }
        public string FileHeader { get; set; }
        public string SystemHeader { get; set; }
    }
}
