//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallsData
    {
        public string Dialer { get; set; }
        public string Picker { get; set; }
        public System.DateTime DateTime { get; set; }
        public System.DateTime TalkTime { get; set; }
        public string Duration { get; set; }
        public string Billing { get; set; }
        public int Cost { get; set; }
        public string Status { get; set; }
        public string CallDetail { get; set; }
    }
}
