//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACC_ACCOUNTEntities : DbContext
    {
        public ACC_ACCOUNTEntities()
            : base("name=ACC_ACCOUNTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendence> Attendences { get; set; }
        public virtual DbSet<BankCode> BankCodes { get; set; }
        public virtual DbSet<BankFormatSheetMapping> BankFormatSheetMappings { get; set; }
        public virtual DbSet<BankHeadersDetail> BankHeadersDetails { get; set; }
        public virtual DbSet<CallDetail> CallDetails { get; set; }
        public virtual DbSet<callFromCode> callFromCodes { get; set; }
        public virtual DbSet<CategoryTypeSheetMapping> CategoryTypeSheetMappings { get; set; }
        public virtual DbSet<contactThrougCode> contactThrougCodes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomersData> CustomersDatas { get; set; }
        public virtual DbSet<CustomersOld> CustomersOlds { get; set; }
        public virtual DbSet<detail_status> detail_status { get; set; }
        public virtual DbSet<ExcelSheetLog> ExcelSheetLogs { get; set; }
        public virtual DbSet<field_visit> field_visit { get; set; }
        public virtual DbSet<field_visit_officer> field_visit_officer { get; set; }
        public virtual DbSet<field_visit_report> field_visit_report { get; set; }
        public virtual DbSet<field_visit_report_images> field_visit_report_images { get; set; }
        public virtual DbSet<IgnoreWordList> IgnoreWordLists { get; set; }
        public virtual DbSet<Landline_No_Details> Landline_No_Details { get; set; }
        public virtual DbSet<Ncri_Staff> Ncri_Staff { get; set; }
        public virtual DbSet<payment_frequency> payment_frequency { get; set; }
        public virtual DbSet<Payment_Plan_Record> Payment_Plan_Record { get; set; }
        public virtual DbSet<Payment_Record> Payment_Record { get; set; }
        public virtual DbSet<PHONE_EXTENSION> PHONE_EXTENSION { get; set; }
        public virtual DbSet<ProductTypeSheetMapping> ProductTypeSheetMappings { get; set; }
        public virtual DbSet<PTCL_Data> PTCL_Data { get; set; }
        public virtual DbSet<ptcl_data_recived> ptcl_data_recived { get; set; }
        public virtual DbSet<recieverCode> recieverCodes { get; set; }
        public virtual DbSet<RegisteredBankCode> RegisteredBankCodes { get; set; }
        public virtual DbSet<SheetDatabaseMapping> SheetDatabaseMappings { get; set; }
        public virtual DbSet<special_access> special_access { get; set; }
        public virtual DbSet<Target> Targets { get; set; }
        public virtual DbSet<TrackRecord> TrackRecords { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<visitStatusCode> visitStatusCodes { get; set; }
        public virtual DbSet<Allocation> Allocations { get; set; }
        public virtual DbSet<CallsData> CallsDatas { get; set; }
        public virtual DbSet<CollectorsCallsData> CollectorsCallsDatas { get; set; }
        public virtual DbSet<Hourly_Report> Hourly_Report { get; set; }
        public virtual DbSet<Report_Table> Report_Table { get; set; }
        public virtual DbSet<test1> test1 { get; set; }
    }
}
