//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_visit_report
    {
        public int id { get; set; }
        public string case_no { get; set; }
        public Nullable<byte> contact_status { get; set; }
        public string person_contacted { get; set; }
        public string customer_contact { get; set; }
        public string third_party_contact { get; set; }
        public string email { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<byte> isHopeful { get; set; }
        public string remarks { get; set; }
        public string new_address { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int sentToCollector { get; set; }
    }
}
