//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hourly_Report
    {
        public string Collector { get; set; }
        public string Bank { get; set; }
        public Nullable<int> Quarter_One { get; set; }
        public Nullable<int> Quarter_Two { get; set; }
        public Nullable<int> Quarter_Three { get; set; }
        public Nullable<int> Quarter_Four { get; set; }
    }
}
