//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_it_departmentEntities : DbContext
    {
        public db_it_departmentEntities()
            : base("name=db_it_departmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_actions> tbl_actions { get; set; }
        public virtual DbSet<tbl_controllers> tbl_controllers { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
    }
}
