//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Landline_No_Details
    {
        public string Name { get; set; }
        public Nullable<int> collectorid { get; set; }
        public string Office_Extension { get; set; }
        public string Landline_No { get; set; }
        public string Status { get; set; }
    }
}
