//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_frequency
    {
        public int id { get; set; }
        public string payment_frequency1 { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> weeks { get; set; }
    }
}
