//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Plan_Record
    {
        public int id { get; set; }
        public string Installment_No_ { get; set; }
        public string Amount { get; set; }
        public string caseid { get; set; }
        public string Account_No_ { get; set; }
        public string CIF { get; set; }
        public string Customer_Name { get; set; }
        public string Product_Type { get; set; }
        public string Bankname { get; set; }
        public string Collectorname { get; set; }
        public string Supervisorname { get; set; }
        public Nullable<System.DateTime> paymentdate { get; set; }
    }
}
