//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTCL_Data
    {
        public int id { get; set; }
        public string CaseId { get; set; }
        public string Customer_Name { get; set; }
        public string Account_No_ { get; set; }
        public string CIF { get; set; }
        public string Defualter_CNIC { get; set; }
        public string Mobile_Number { get; set; }
        public string Debtor_Email_Address { get; set; }
        public string Debtor_Phone__ { get; set; }
        public Nullable<System.DateTime> date_requested { get; set; }
        public string collectorname { get; set; }
    }
}
