//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Table
    {
        public string Collector { get; set; }
        public Nullable<int> Total_AC { get; set; }
        public Nullable<int> Allocated_AC_Bw_Period { get; set; }
        public string Bank { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> MTD_Ach { get; set; }
        public Nullable<int> Contactable { get; set; }
        public Nullable<int> Non_Contactable { get; set; }
        public Nullable<int> Skip_Trace { get; set; }
        public Nullable<int> Worked { get; set; }
        public Nullable<int> Not_Worked { get; set; }
        public string Percentage { get; set; }
        public Nullable<int> Ach_New_Clients { get; set; }
        public Nullable<int> Ach_Settlement_Clients { get; set; }
        public Nullable<int> Total_PTP_Count { get; set; }
        public Nullable<int> Total_PTP_Amount { get; set; }
        public Nullable<int> UNG_Clients { get; set; }
        public Nullable<int> TPC_Clients { get; set; }
        public Nullable<int> BPTP_Clients { get; set; }
        public Nullable<int> RNR_Clients { get; set; }
    }
}
