//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SheetDatabaseMapping
    {
        public int id { get; set; }
        public string bankName { get; set; }
        public string sheetMappingColumn { get; set; }
        public string sheetMappingColumnName { get; set; }
        public Nullable<int> sheetMappingColumnLocation { get; set; }
        public string databaseMappingColumn { get; set; }
        public Nullable<bool> isSearchableColumn { get; set; }
        public Nullable<bool> isUpdatableColumn { get; set; }
        public string excelFileName { get; set; }
        public string filePath { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
