//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        public int id { get; set; }
        public string Supervisor { get; set; }
        public string collector_name { get; set; }
        public Nullable<double> Target1 { get; set; }
        public Nullable<int> Coverage { get; set; }
        public Nullable<int> skiptrace { get; set; }
        public Nullable<int> payee_count { get; set; }
        public Nullable<System.TimeSpan> work_hrs { get; set; }
        public Nullable<int> total_calls { get; set; }
        public Nullable<double> collected_value { get; set; }
        public string designation { get; set; }
        public Nullable<int> working_days { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> Year { get; set; }
        public string collectorsid { get; set; }
    }
}
