//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class test1
    {
        public int id { get; set; }
        public string detail_status { get; set; }
        public string visitStatus { get; set; }
        public string contactThrough { get; set; }
        public string callFrom { get; set; }
        public string caseId { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string collector { get; set; }
        public string subcodes { get; set; }
        public string fieldOfficer { get; set; }
        public string contactNo { get; set; }
        public string remarks { get; set; }
        public string reciever { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> amount { get; set; }
        public string Bankname { get; set; }
        public string AccountNo_ { get; set; }
        public string Product { get; set; }
        public string CIF { get; set; }
        public string case_status { get; set; }
        public string company_code { get; set; }
        public string Supervisor { get; set; }
        public string Contact_Status { get; set; }
        public Nullable<int> collectorid { get; set; }
    }
}
