//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRI_WEBPORTALFORMISC.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> interaction_time { get; set; }
        public Nullable<int> Session { get; set; }
        public string email { get; set; }
        public string mail_password { get; set; }
        public string mailing_server { get; set; }
        public string phone { get; set; }
        public int type { get; set; }
        public string status { get; set; }
        public string Supervisor { get; set; }
        public string Product { get; set; }
        public Nullable<double> Unique_ACR { get; set; }
        public Nullable<double> Total_ACR { get; set; }
        public Nullable<double> Worked_accounts { get; set; }
        public Nullable<double> Not_worked_accounts { get; set; }
        public Nullable<double> coverage_percentage { get; set; }
        public Nullable<double> CRM_Updates { get; set; }
        public Nullable<double> Target { get; set; }
        public Nullable<double> PTP { get; set; }
        public Nullable<double> Skiptrace { get; set; }
        public Nullable<double> contactable { get; set; }
        public Nullable<int> access_btn_1 { get; set; }
        public Nullable<int> access_btn_2 { get; set; }
        public Nullable<int> access_btn_3 { get; set; }
        public Nullable<int> access_btn_4 { get; set; }
        public Nullable<int> access_btn_5 { get; set; }
        public Nullable<int> access_btn_6 { get; set; }
        public Nullable<int> access_btn_7 { get; set; }
        public Nullable<int> access_btn_8 { get; set; }
        public Nullable<int> access_btn_9 { get; set; }
        public Nullable<int> access_btn_10 { get; set; }
        public Nullable<int> access_btn_11 { get; set; }
        public Nullable<int> access_btn_12 { get; set; }
        public Nullable<int> access_btn_13 { get; set; }
        public Nullable<int> access_btn_14 { get; set; }
        public Nullable<int> access_btn_15 { get; set; }
        public Nullable<int> access_btn_16 { get; set; }
        public Nullable<int> access_btn_17 { get; set; }
        public Nullable<int> access_btn_18 { get; set; }
        public Nullable<int> access_btn_19 { get; set; }
        public Nullable<int> access_btn_20 { get; set; }
        public Nullable<int> fvisit_queue { get; set; }
        public Nullable<int> visit_limit { get; set; }
    }
}
